# Generated by Django 5.2.12 on 2026-05-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='branch',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='section',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='year',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
