# Generated by Django 5.2.12 on 2026-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_quiz_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="fullscreen_exit_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attempt",
            name="fullscreen_violation_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
