from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/login/", views.QuizLoginView.as_view(), name="login"),
    path("student/login/", views.StudentLoginView.as_view(), name="student_login"),
    path("teacher/login/", views.TeacherLoginView.as_view(), name="teacher_login"),
    path("accounts/logout/", views.QuizLogoutView.as_view(), name="logout"),
    path("accounts/register/", views.register, name="register"),
    path("student/register/", views.register, name="student_register"),
    path("teacher/register/", views.teacher_register, name="teacher_register"),
    path("student/dashboard/", views.student_dashboard, name="student_dashboard"),
    path("student/upcoming/", views.student_upcoming_quizzes, name="student_upcoming_quizzes"),
    path("student/results/", views.student_results, name="student_results"),
    path("student/leaderboards/", views.student_leaderboards, name="student_leaderboards"),
    path("quizzes/", views.quiz_list, name="quiz_list"),
    path("quizzes/<int:quiz_id>/", views.quiz_instruction, name="quiz_instruction"),
    path("quizzes/<int:quiz_id>/start/", views.start_quiz, name="start_quiz"),
    path("attempts/<int:attempt_id>/question/<int:position>/", views.attempt_question, name="attempt_question"),
    path("attempts/<int:attempt_id>/save/", views.save_answer, name="save_answer"),
    path("attempts/<int:attempt_id>/tab-warning/", views.log_tab_switch, name="log_tab_switch"),
    path("attempts/<int:attempt_id>/submit/", views.submit_attempt, name="submit_attempt"),
    path("attempts/<int:attempt_id>/result/", views.result, name="result"),
    path("quizzes/<int:quiz_id>/leaderboard/", views.leaderboard, name="leaderboard"),
    path("teacher/dashboard/", views.teacher_dashboard, name="teacher_dashboard"),
    path("dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("teacher/quizzes/", views.teacher_quiz_list, name="teacher_quiz_list"),
    path("teacher/students/", views.teacher_student_list, name="teacher_student_list"),
    path("teacher/results/", views.teacher_results_overview, name="teacher_results_overview"),
    path("teacher/quizzes/add/", views.teacher_quiz_create, name="teacher_quiz_create"),
    path("teacher/quizzes/<int:quiz_id>/edit/", views.teacher_quiz_update, name="teacher_quiz_update"),
    path("teacher/quizzes/<int:quiz_id>/delete/", views.teacher_quiz_delete, name="teacher_quiz_delete"),
    path("teacher/quizzes/<int:quiz_id>/questions/", views.teacher_question_list, name="teacher_question_list"),
    path("teacher/quizzes/<int:quiz_id>/questions/add/", views.teacher_question_create, name="teacher_question_create"),
    path("teacher/quizzes/<int:quiz_id>/questions/<int:question_id>/edit/", views.teacher_question_update, name="teacher_question_update"),
    path("teacher/quizzes/<int:quiz_id>/questions/<int:question_id>/delete/", views.teacher_question_delete, name="teacher_question_delete"),
    path("teacher/quizzes/<int:quiz_id>/results/", views.teacher_quiz_results, name="teacher_quiz_results"),
    path("teacher/dashboard/export/", views.export_results_csv, name="export_results_csv"),
    path("teacher/quizzes/<int:quiz_id>/export/", views.export_quiz_results_csv, name="export_quiz_results_csv"),
    path("dashboard/export/", views.export_results_csv, name="legacy_export_results_csv"),
]
